curl https://xujiaqi123.netlify.app/v1/models/gemini-pro:generateContent?key=AIzaSyBrrREtlM6XT4Iy0AsGKU4_xOyS1bAocBQ \
   -H 'Content-Type: application/json' \
   -X POST \
   -d '{ "contents":[
   { "parts":[{"text": "Hi"}]}
   ]
}'

curl https://xujiaqi123.netlify.app/v1/models/gemini-pro:streamGenerateContent?key=AIzaSyBrrREtlM6XT4Iy0AsGKU4_xOyS1bAocBQ&alt=sse \
   -H 'Content-Type: application/json' \
   --no-buffer \
   -d '{ "contents":[
         {"role": "user",
            "parts":[{"text": "Hi"}]
         }
         ]
      }' > response.json
